spring:
  application:
    name: ecommerce-monolithic

  datasource:
    username: root
    password: Dungthieu1972
    url: jdbc:mysql://localhost:3306/ecommerce-monolithic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8081
  error:
    include-message: always
openapi:
  service:
    title: user-service doc # title that you will want to display in the Swagger UI
    version: 1.0.0
    url: http://192.168.1.42:8081
springdoc:
  api-docs:
    path: /users/v3/api-docs
  swagger-ui:
    path: /users/swagger-ui.html
