spring:
  application:
    name: user-service

  datasource:
    username: root
    password: Dungthieu1972
    url: jdbc:mysql://localhost:3306/EA-user-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8081
  error:
    include-message: always
